export const countryList = [
    { "한국": "South Korea" },
    { "미국": "United States" },
    { "캐나다": "Canada" },
    { "멕시코": "Mexico" },
    { "브라질": "Brazil" },
    { "아르헨티나": "Argentina" },
    { "영국": "United Kingdom" },
    { "프랑스": "France" },
    { "독일": "Germany" },
    { "이탈리아": "Italy" },
    { "스페인": "Spain" },
    { "러시아": "Russia" },
    { "중국": "China" },
    { "일본": "Japan" },
    { "호주": "Australia" },
    { "인도": "India" },
    { "남아프리카 공화국": "South Africa" },
    { "이집트": "Egypt" },
    { "나이지리아": "Nigeria" },
    { "사우디아라비아": "Saudi Arabia" },
    { "아랍에미리트": "United Arab Emirates" },
    { "터키": "Turkey" },
    { "인도네시아": "Indonesia" },
    { "태국": "Thailand" },
    { "베트남": "Vietnam" },
    { "필리핀": "Philippines" },
    { "말레이시아": "Malaysia" },
    { "싱가포르": "Singapore" },
    { "뉴질랜드": "New Zealand" },
    { "스웨덴": "Sweden" },
    { "스위스": "Switzerland" },
    { "네덜란드": "Netherlands" },
    { "벨기에": "Belgium" },
    { "오스트리아": "Austria" },
    { "덴마크": "Denmark" },
    { "노르웨이": "Norway" },
    { "핀란드": "Finland" },
    { "아일랜드": "Ireland" },
    { "포르투갈": "Portugal" },
    { "그리스": "Greece" },
    { "폴란드": "Poland" },
    { "헝가리": "Hungary" },
    { "체코": "Czech Republic" },
    { "루마니아": "Romania" },
    { "불가리아": "Bulgaria" },
    { "크로아티아": "Croatia" },
    { "세르비아": "Serbia" },
    { "슬로바키아": "Slovakia" },
    { "슬로베니아": "Slovenia" },
    { "에스토니아": "Estonia" },
    { "라트비아": "Latvia" },
    { "리투아니아": "Lithuania" },
    { "룩셈부르크": "Luxembourg" },
    { "몰타": "Malta" },
    { "아이슬란드": "Iceland" },
    { "모나코": "Monaco" },
    { "리히텐슈타인": "Liechtenstein" },
    { "산마리노": "San Marino" },
    { "바티칸 시국": "Vatican City" },
    { "안도라": "Andorra" },
    { "키프로스": "Cyprus" },
    { "몰도바": "Moldova" },
    { "알바니아": "Albania" },
    { "북마케도니아": "North Macedonia" },
    { "보스니아 헤르체고비나": "Bosnia and Herzegovina" },
    { "몬테네그로": "Montenegro" },
    { "코소보": "Kosovo" },
    { "벨라루스": "Belarus" },
    { "우크라이나": "Ukraine" },
    { "조지아": "Georgia" },
    { "아르메니아": "Armenia" },
    { "아제르바이잔": "Azerbaijan" },
    { "카자흐스탄": "Kazakhstan" },
    { "우즈베키스탄": "Uzbekistan" },
    { "투르크메니스탄": "Turkmenistan" },
    { "타지키스탄": "Tajikistan" },
    { "키르기스스탄": "Kyrgyzstan" },
    { "몽골": "Mongolia" },
    { "방글라데시": "Bangladesh" },
    { "파키스탄": "Pakistan" },
    { "네팔": "Nepal" },
    { "부탄": "Bhutan" },
    { "스리랑카": "Sri Lanka" },
    { "몰디브": "Maldives" },
    { "미얀마": "Myanmar" },
    { "캄보디아": "Cambodia" },
    { "라오스": "Laos" },
    { "브루나이": "Brunei" },
    { "동티모르": "East Timor" },
    { "피지": "Fiji" },
    { "파푸아뉴기니": "Papua New Guinea" },
    { "솔로몬 제도": "Solomon Islands" },
    { "바누아투": "Vanuatu" },
    { "사모아": "Samoa" },
    { "통가": "Tonga" },
    { "키리바시": "Kiribati" },
    { "마셜 제도": "Marshall Islands" },
    { "미크로네시아 연방": "Federated States of Micronesia" },
    { "팔라우": "Palau" },
    { "나우루": "Nauru" },
    { "투발루": "Tuvalu" },
    { "쿡 제도": "Cook Islands" },
    { "니우에": "Niue" },
    { "토켈라우": "Tokelau" },
    { "바베이도스": "Barbados" },
    { "앤티가 바부다": "Antigua and Barbuda" },
    { "세인트키츠 네비스": "Saint Kitts and Nevis" },
    { "도미니카 연방": "Dominica" },
    { "세인트루시아": "Saint Lucia" },
    { "세인트빈센트 그레나딘": "Saint Vincent and the Grenadines" },
    { "그레나다": "Grenada" },
    { "바하마": "Bahamas" },
    { "아이티": "Haiti" },
    { "도미니카 공화국": "Dominican Republic" },
    { "쿠바": "Cuba" },
    { "자메이카": "Jamaica" },
    { "트리니다드 토바고": "Trinidad and Tobago" },
    { "벨리즈": "Belize" },
    { "코스타리카": "Costa Rica" },
    { "엘살바도르": "El Salvador" },
    { "과테말라": "Guatemala" },
    { "온두라스": "Honduras" },
    { "니카라과": "Nicaragua" },
    { "파나마": "Panama" },
    { "콜롬비아": "Colombia" },
    { "베네수엘라": "Venezuela" },
    { "에콰도르": "Ecuador" },
    { "페루": "Peru" },
    { "볼리비아": "Bolivia" },
    { "칠레": "Chile" },
    { "파라과이": "Paraguay" },
    { "우루과이": "Uruguay" },
    { "가이아나": "Guyana" },
    { "수리남": "Suriname" },
    { "모로코": "Morocco" },
    { "알제리": "Algeria" },
    { "튀니지": "Tunisia" },
    { "리비아": "Libya" },
    { "수단": "Sudan" },
    { "남수단": "South Sudan" },
    { "에티오피아": "Ethiopia" },
    { "케냐": "Kenya" },
    { "탄자니아": "Tanzania" },
    { "우간다": "Uganda" },
    { "르완다": "Rwanda" },
    { "부룬디": "Burundi" },
    { "소말리아": "Somalia" },
    { "지부티": "Djibouti" },
    { "에리트레아": "Eritrea" },
    { "세이셸": "Seychelles" },
    { "코모로": "Comoros" },
    { "모리셔스": "Mauritius" },
    { "마다가스카르": "Madagascar" },
    { "말라위": "Malawi" },
    { "잠비아": "Zambia" },
    { "짐바브웨": "Zimbabwe" },
    { "보츠와나": "Botswana" },
    { "나미비아": "Namibia" },
    { "에스와티니": "Eswatini" },
    { "레소토": "Lesotho" },
    { "앙골라": "Angola" },
    { "모잠비크": "Mozambique" },
    { "가봉": "Gabon" },
    { "콩고 공화국": "Republic of the Congo" },
    { "콩고 민주 공화국": "Democratic Republic of the Congo" },
    { "카메룬": "Cameroon" },
    { "중앙아프리카 공화국": "Central African Republic" },
    { "차드": "Chad" },
    { "니제르": "Niger" },
    { "베냉": "Benin" },
    { "토고": "Togo" },
    { "가나": "Ghana" },
    { "코트디부아르": "Ivory Coast" },
    { "부르키나파소": "Burkina Faso" },
    { "기니": "Guinea" },
    { "기니비사우": "Guinea-Bissau" },
    { "시에라리온": "Sierra Leone" },
    { "라이베리아": "Liberia" },
    { "말리": "Mali" },
    { "모리타니": "Mauritania" },
    { "세네갈": "Senegal" },
    { "감비아": "Gambia" },
    { "카보베르데": "Cape Verde" },
    { "상투메 프린시페": "Sao Tome and Principe" },
    { "적도 기니": "Equatorial Guinea" },
    { "이스라엘": "Israel" },
    { "팔레스타인": "Palestine" },
    { "요르단": "Jordan" },
    { "레바논": "Lebanon" },
    { "시리아": "Syria" },
    { "이라크": "Iraq" },
    { "이란": "Iran" },
    { "아프가니스탄": "Afghanistan" },
    { "오만": "Oman" },
    { "카타르": "Qatar" },
    { "쿠웨이트": "Kuwait" },
    { "바레인": "Bahrain" },
    { "예멘": "Yemen" },
    { "타이완": "Taiwan" },
    { "홍콩": "Hong Kong" },
    { "마카오": "Macau" },
    { "스리랑카": "Sri Lanka" },
    { "몰디브": "Maldives" },
    { "부탄": "Bhutan" },
    { "네팔": "Nepal" },
    { "방글라데시": "Bangladesh" },
    { "파키스탄": "Pakistan" },
    { "키르기스스탄": "Kyrgyzstan" },
    { "타지키스탄": "Tajikistan" },
    { "투르크메니스탄": "Turkmenistan" },
    { "우즈베키스탄": "Uzbekistan" },
    { "카자흐스탄": "Kazakhstan" },
    { "몽골": "Mongolia" },
    { "미얀마": "Myanmar" },
    { "태국": "Thailand" },
    { "라오스": "Laos" },
    { "캄보디아": "Cambodia" },
    { "베트남": "Vietnam" },
    { "말레이시아": "Malaysia" },
    { "싱가포르": "Singapore" },
    { "브루나이": "Brunei" },
    { "필리핀": "Philippines" },
    { "인도네시아": "Indonesia" },
    { "동티모르": "East Timor" },
    { "호주": "Australia" },
    { "뉴질랜드": "New Zealand" },
    { "피지": "Fiji" },
    { "파푸아뉴기니": "Papua New Guinea" },
    { "솔로몬 제도": "Solomon Islands" },
    { "바누아투": "Vanuatu" },
    { "사모아": "Samoa" },
    { "통가": "Tonga" },
    { "키리바시": "Kiribati" },
    { "마셜 제도": "Marshall Islands" },
    { "미크로네시아 연방": "Federated States of Micronesia" },
    { "팔라우": "Palau" },
    { "나우루": "Nauru" },
    { "투발루": "Tuvalu" },
    { "쿡 제도": "Cook Islands" },
    { "니우에": "Niue" },
    { "토켈라우": "Tokelau" }
  ]