name: front-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
    paths:
      - "front/**"

jobs:
  build:
    strategy:
      matrix:
        node: ['18', '22']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: front/node_modules
          key: |
            ${{ runner.os }}-build-${{ hashFiles('front/package-lock.json') }}
          restore-keys: | 
            ${{ runner.os }}-build-${{ hashFiles('front/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run build
        run: npm run build
